server.port=8081
weather.api.key=1f47cc16792c1b3ffd364e6deb4c7c47
weather.api.url=https://api.openweathermap.org/data/2.5/weather

spring.datasource.url=jdbc:mysql://localhost:3306/weather_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
